# Generated by Django 3.1.2 on 2020-10-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medico',
        ),
    ]
