# Generated by Django 3.1.2 on 2020-10-15 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aplicacion', '0002_delete_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaCita', models.DateField()),
                ('TipoCita', models.CharField(blank=True, max_length=100)),
                ('Observaciones', models.CharField(max_length=500)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Cedula', models.IntegerField()),
                ('Correo', models.EmailField(blank=True, max_length=254)),
                ('TipoSangre', models.CharField(max_length=10)),
                ('Telefono', models.CharField(max_length=15)),
                ('Celular', models.CharField(max_length=15)),
                ('FechaNacimiento', models.DateField()),
                ('Especialidad', models.CharField(max_length=50)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resultados', models.CharField(max_length=500)),
                ('FechaExamen', models.DateField()),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoFamiliar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Titular', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=120)),
                ('Sede', models.CharField(max_length=500)),
                ('Direccion', models.CharField(max_length=500)),
                ('Horario', models.CharField(max_length=120)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Cedula', models.IntegerField()),
                ('Correo', models.EmailField(blank=True, max_length=254)),
                ('TipoSangre', models.CharField(max_length=10)),
                ('Telefono', models.CharField(max_length=15)),
                ('Celular', models.CharField(max_length=15)),
                ('FechaNacimiento', models.DateField()),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sintomas', models.CharField(max_length=500)),
                ('Medicamentos', models.CharField(max_length=500)),
                ('SignosVitales', models.CharField(max_length=500)),
                ('Generacion', models.CharField(max_length=500)),
                ('Incapacitaciones', models.CharField(max_length=500, null=True)),
                ('Remisiones', models.CharField(max_length=500, null=True)),
                ('OrdenesMedicas', models.CharField(max_length=500)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=20)),
                ('Contraseña', models.CharField(max_length=20)),
                ('TipoUsuario', models.CharField(choices=[('Medico', 'Medico'), ('Paciente', 'Paciente'), ('Especialista', 'Especialista')], default='Medico', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Cedula', models.IntegerField()),
                ('Correo', models.EmailField(max_length=254)),
                ('TipoSangre', models.CharField(max_length=10)),
                ('Telefono', models.CharField(max_length=15)),
                ('Celular', models.CharField(max_length=15)),
                ('FechaNacimiento', models.DateField()),
                ('Estrato', models.IntegerField()),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
                ('IdGrupoFamiliar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.grupofamiliar', verbose_name='Identificador del GrupoFamiliar')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
                ('IdCita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.cita', verbose_name='Identificador de la Cita')),
                ('IdExamen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.examen', verbose_name='Identificador del Examen')),
                ('IdPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.paciente', verbose_name='Identificador del Paciente')),
            ],
        ),
        migrations.AddField(
            model_name='grupofamiliar',
            name='IdMedico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.medico', verbose_name='Identificador del Medico'),
        ),
        migrations.AddField(
            model_name='examen',
            name='IdLaboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.laboratorio', verbose_name='Identificador del Laboratorio'),
        ),
        migrations.AddField(
            model_name='examen',
            name='IdPaciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.paciente', verbose_name='Identificador del Paciente'),
        ),
        migrations.CreateModel(
            name='CitaEspecialista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaCita', models.DateField()),
                ('TipoCita', models.CharField(max_length=100)),
                ('Observaciones', models.CharField(max_length=500)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
                ('IdEspecialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.especialista', verbose_name='Identificador del Especialista')),
                ('IdPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.paciente', verbose_name='Identificador del Paciente')),
                ('IdRegistro', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.registro', verbose_name='Identificador del Registro')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='IdMedico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.medico', verbose_name='Identificador del Medico'),
        ),
        migrations.AddField(
            model_name='cita',
            name='IdPaciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.paciente', verbose_name='Identificador del Paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='IdRegistro',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.registro', verbose_name='Identificador del Registro'),
        ),
    ]
